// Code generated by ent, DO NOT EDIT.

package token

import (
	"webapp/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Token {
	return predicate.Token(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Token {
	return predicate.Token(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Token {
	return predicate.Token(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Token {
	return predicate.Token(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Token {
	return predicate.Token(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Token {
	return predicate.Token(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Token {
	return predicate.Token(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Token {
	return predicate.Token(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Token {
	return predicate.Token(sql.FieldLTE(FieldID, id))
}

// Val applies equality check predicate on the "val" field. It's identical to ValEQ.
func Val(v string) predicate.Token {
	return predicate.Token(sql.FieldEQ(FieldVal, v))
}

// ValEQ applies the EQ predicate on the "val" field.
func ValEQ(v string) predicate.Token {
	return predicate.Token(sql.FieldEQ(FieldVal, v))
}

// ValNEQ applies the NEQ predicate on the "val" field.
func ValNEQ(v string) predicate.Token {
	return predicate.Token(sql.FieldNEQ(FieldVal, v))
}

// ValIn applies the In predicate on the "val" field.
func ValIn(vs ...string) predicate.Token {
	return predicate.Token(sql.FieldIn(FieldVal, vs...))
}

// ValNotIn applies the NotIn predicate on the "val" field.
func ValNotIn(vs ...string) predicate.Token {
	return predicate.Token(sql.FieldNotIn(FieldVal, vs...))
}

// ValGT applies the GT predicate on the "val" field.
func ValGT(v string) predicate.Token {
	return predicate.Token(sql.FieldGT(FieldVal, v))
}

// ValGTE applies the GTE predicate on the "val" field.
func ValGTE(v string) predicate.Token {
	return predicate.Token(sql.FieldGTE(FieldVal, v))
}

// ValLT applies the LT predicate on the "val" field.
func ValLT(v string) predicate.Token {
	return predicate.Token(sql.FieldLT(FieldVal, v))
}

// ValLTE applies the LTE predicate on the "val" field.
func ValLTE(v string) predicate.Token {
	return predicate.Token(sql.FieldLTE(FieldVal, v))
}

// ValContains applies the Contains predicate on the "val" field.
func ValContains(v string) predicate.Token {
	return predicate.Token(sql.FieldContains(FieldVal, v))
}

// ValHasPrefix applies the HasPrefix predicate on the "val" field.
func ValHasPrefix(v string) predicate.Token {
	return predicate.Token(sql.FieldHasPrefix(FieldVal, v))
}

// ValHasSuffix applies the HasSuffix predicate on the "val" field.
func ValHasSuffix(v string) predicate.Token {
	return predicate.Token(sql.FieldHasSuffix(FieldVal, v))
}

// ValEqualFold applies the EqualFold predicate on the "val" field.
func ValEqualFold(v string) predicate.Token {
	return predicate.Token(sql.FieldEqualFold(FieldVal, v))
}

// ValContainsFold applies the ContainsFold predicate on the "val" field.
func ValContainsFold(v string) predicate.Token {
	return predicate.Token(sql.FieldContainsFold(FieldVal, v))
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.Token {
	return predicate.Token(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.User) predicate.Token {
	return predicate.Token(func(s *sql.Selector) {
		step := newOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Token) predicate.Token {
	return predicate.Token(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Token) predicate.Token {
	return predicate.Token(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Token) predicate.Token {
	return predicate.Token(func(s *sql.Selector) {
		p(s.Not())
	})
}
